sudo: false
language: python
python:
- '3.5'
matrix:
  allow_failures:
  - env: TOXENV=py27-django110-sqlite
  - env: TOXENV=py27-django110-mysql
  - env: TOXENV=py27-django110-postgresql
  - env: TOXENV=py34-django110-sqlite
  - env: TOXENV=py34-django110-mysql
  - env: TOXENV=py34-django110-postgresql
env:
  matrix:
  - TOXENV=py27-django18-sqlite
  - TOXENV=py27-django18-mysql
  - TOXENV=py27-django18-postgresql
  - TOXENV=py27-django19-sqlite
  - TOXENV=py27-django19-mysql
  - TOXENV=py27-django19-postgresql
  - TOXENV=py27-django110-sqlite
  - TOXENV=py27-django110-mysql
  - TOXENV=py27-django110-postgresql
  - TOXENV=py34-django18-sqlite
  - TOXENV=py34-django18-mysql
  - TOXENV=py34-django18-postgresql
  - TOXENV=py34-django19-sqlite
  - TOXENV=py34-django19-mysql
  - TOXENV=py34-django19-postgresql
  - TOXENV=py34-django110-sqlite
  - TOXENV=py34-django110-mysql
  - TOXENV=py34-django110-postgresql
  - TOXENV=checkqa
  - TOXENV=docs
install:
- pip install -U pip
- pip install tox codecov
script:
- tox
after_success:
- codecov
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
notifications:
  irc:
    channels:
    - irc.freenode.org#yourlabs
    template:
    - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
