sudo: false
language: python
matrix:
  allow_failures:
  - env: TOXENV=py37-djangodev-sqlite
  - env: TOXENV=py37-djangodev-mysql
  - env: TOXENV=py37-djangodev-postgresql
  include:
  - python: 3.7
    env: TOX_ENV=py37-django111-sqlite
  - python: 3.7
    env: TOX_ENV=py37-django20-sqlite
  - python: 3.7
    env: TOX_ENV=py37-django30-sqlite
  - python: 3.8
    env: TOX_ENV=py38-django30-sqlite
  - python: 3.7
    env: TOX_ENV=py37-djangodev-sqlite
  - python: 3.7
    env: TOX_ENV=py37-djangodev-mysql
  - python: 3.7
    env: TOX_ENV=py37-djangodev-postgresql
  - python: 3.7
    env: TOX_ENV=checkqa
  - python: 3.7
    env: TOX_ENV=docs
install:
- pip install -U pip
- pip install tox codecov
script:
- tox
after_success:
- codecov
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
notifications:
  irc:
    channels:
    - irc.freenode.org#yourlabs
    template:
    - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
